version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: Expensemongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: Admin123
    ports:
      - 27017:27017
    # networks:
    #   - mynetwork
    volumes:
      - ./mongodb:/data/db

# networks:
#   mynetwork:
#     external: true
